//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesHastahane
{
    using System;
    using System.Collections.Generic;
    
    public partial class hastakayıt
    {
        public int IDNO { get; set; }
        public string DOKTORADI { get; set; }
        public string HASTADI { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public Nullable<decimal> UCRET { get; set; }
    }
}
